Correção do horário
Maua-Dev/dev_medias_back pull request #51
Opened 2024-10-30 22:52 UTC by gioalbuquerque

2024-11-01 02:15 UTC, VgsStudio requested changes

2024-11-01 02:15 UTC, VgsStudio commented on lambda_function/contact_us/app/send_email_feedback_presenter.py
> +import pytz
Por conta da layer, eu acho que vamos ter problemas com o pacote do pytz, quer dar deploy e testar ou trocar por uma utilziação sem o pytz?

ele só seta o valor do delta no datetime, ele abstrai isso

2024-11-02 16:25 UTC, gioalbuquerque commented on lambda_function/contact_us/app/send_email_feedback_presenter.py
> +import pytz
o que você acha que vale mais a pena Soller ?

2024-12-12 23:02 UTC, VgsStudio commented on lambda_function/contact_us/app/send_email_feedback_presenter.py
> +import pytz
seta na mao o timezone

2026-07-06 14:25 UTC, closed without merging